// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/(gr-cu)/gestionar-referencias/index.tsx";
import * as $1 from "./routes/(is-cu)/inicio-sesion/cerrar-sesion.ts";
import * as $2 from "./routes/(is-cu)/inicio-sesion/index.tsx";
import * as $3 from "./routes/(is-cu)/inicio-sesion/iniciar-sesion.tsx";
import * as $4 from "./routes/(is-cu)/inicio-sesion/registrar.tsx";
import * as $5 from "./routes/_404.tsx";
import * as $6 from "./routes/_app.tsx";
import * as $7 from "./routes/_layout.tsx";
import * as $8 from "./routes/_middleware.ts";
import * as $9 from "./routes/api/_middleware.ts";
import * as $10 from "./routes/api/bibliographie/[id].tsx";
import * as $11 from "./routes/api/bibliographie/file/[id].tsx";
import * as $12 from "./routes/api/bibliographie/file/index.ts";
import * as $13 from "./routes/api/bibliographie/index.ts";
import * as $14 from "./routes/api/index.ts";
import * as $15 from "./routes/index.ts";
import * as $$0 from "./islands/Input.tsx";
import * as $$1 from "./islands/PaginationButtons.tsx";
import * as $$2 from "./islands/Select.tsx";
import * as $$3 from "./islands/SessionProvider.tsx";
import * as $$4 from "./islands/gr-cu/DeleteReferenceDialog.tsx";
import * as $$5 from "./islands/gr-cu/DownloadFileButton.tsx";
import * as $$6 from "./islands/gr-cu/ReferencesManagement.tsx";
import * as $$7 from "./islands/gr-cu/gr-cb-cu/CreateReferenceButton.tsx";
import * as $$8 from "./islands/gr-cu/gr-cb-cu/ReferenceDialog.tsx";
import * as $$9 from "./islands/gr-cu/gr-cb-cu/ReferenceForm.tsx";
import * as $$10 from "./islands/is-cu/LoginForm.tsx";
import * as $$11 from "./islands/is-cu/RegisterForm.tsx";

const manifest = {
  routes: {
    "./routes/(gr-cu)/gestionar-referencias/index.tsx": $0,
    "./routes/(is-cu)/inicio-sesion/cerrar-sesion.ts": $1,
    "./routes/(is-cu)/inicio-sesion/index.tsx": $2,
    "./routes/(is-cu)/inicio-sesion/iniciar-sesion.tsx": $3,
    "./routes/(is-cu)/inicio-sesion/registrar.tsx": $4,
    "./routes/_404.tsx": $5,
    "./routes/_app.tsx": $6,
    "./routes/_layout.tsx": $7,
    "./routes/_middleware.ts": $8,
    "./routes/api/_middleware.ts": $9,
    "./routes/api/bibliographie/[id].tsx": $10,
    "./routes/api/bibliographie/file/[id].tsx": $11,
    "./routes/api/bibliographie/file/index.ts": $12,
    "./routes/api/bibliographie/index.ts": $13,
    "./routes/api/index.ts": $14,
    "./routes/index.ts": $15,
  },
  islands: {
    "./islands/Input.tsx": $$0,
    "./islands/PaginationButtons.tsx": $$1,
    "./islands/Select.tsx": $$2,
    "./islands/SessionProvider.tsx": $$3,
    "./islands/gr-cu/DeleteReferenceDialog.tsx": $$4,
    "./islands/gr-cu/DownloadFileButton.tsx": $$5,
    "./islands/gr-cu/ReferencesManagement.tsx": $$6,
    "./islands/gr-cu/gr-cb-cu/CreateReferenceButton.tsx": $$7,
    "./islands/gr-cu/gr-cb-cu/ReferenceDialog.tsx": $$8,
    "./islands/gr-cu/gr-cb-cu/ReferenceForm.tsx": $$9,
    "./islands/is-cu/LoginForm.tsx": $$10,
    "./islands/is-cu/RegisterForm.tsx": $$11,
  },
  baseUrl: import.meta.url,
};

export default manifest;
