// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/(gc-cu)/gestionar-carpetas/(gc-gr-cu)/[id].tsx";
import * as $1 from "./routes/(gc-cu)/gestionar-carpetas/index.tsx";
import * as $2 from "./routes/(gg-cu)/gestionar-grupos/index.tsx";
import * as $3 from "./routes/(gr-cu)/gestionar-referencias/index.tsx";
import * as $4 from "./routes/(is-cu)/inicio-sesion/cerrar-sesion.ts";
import * as $5 from "./routes/(is-cu)/inicio-sesion/index.tsx";
import * as $6 from "./routes/(is-cu)/inicio-sesion/iniciar-sesion.tsx";
import * as $7 from "./routes/(is-cu)/inicio-sesion/registrar.tsx";
import * as $8 from "./routes/_404.tsx";
import * as $9 from "./routes/_app.tsx";
import * as $10 from "./routes/_layout.tsx";
import * as $11 from "./routes/_middleware.ts";
import * as $12 from "./routes/about.tsx";
import * as $13 from "./routes/api/_middleware.ts";
import * as $14 from "./routes/api/bibliographie/[id].tsx";
import * as $15 from "./routes/api/bibliographie/file/[id].tsx";
import * as $16 from "./routes/api/bibliographie/file/index.ts";
import * as $17 from "./routes/api/bibliographie/index.ts";
import * as $18 from "./routes/api/folder/[id].tsx";
import * as $19 from "./routes/api/folder/index.ts";
import * as $20 from "./routes/api/group/[id].tsx";
import * as $21 from "./routes/api/group/index.ts";
import * as $22 from "./routes/api/index.ts";
import * as $23 from "./routes/index.tsx";
import * as $24 from "./routes/suscription.tsx";
import * as $$0 from "./islands/Input.tsx";
import * as $$1 from "./islands/PaginationButtons.tsx";
import * as $$2 from "./islands/Select.tsx";
import * as $$3 from "./islands/SessionProvider.tsx";
import * as $$4 from "./islands/gc-cu/CreateFolderButton.tsx";
import * as $$5 from "./islands/gc-cu/CreateFolderCard.tsx";
import * as $$6 from "./islands/gc-cu/DeleteFolderDialog.tsx";
import * as $$7 from "./islands/gc-cu/FolderCard.tsx";
import * as $$8 from "./islands/gc-cu/ListFolders.tsx";
import * as $$9 from "./islands/gg-cu/CreateGroupButton.tsx";
import * as $$10 from "./islands/gg-cu/CreateGroupCard.tsx";
import * as $$11 from "./islands/gg-cu/GroupCard.tsx";
import * as $$12 from "./islands/gg-cu/ListGroups.tsx";
import * as $$13 from "./islands/gr-cu/DeleteReferenceDialog.tsx";
import * as $$14 from "./islands/gr-cu/DownloadFileButton.tsx";
import * as $$15 from "./islands/gr-cu/GenerateReferenceButton.tsx";
import * as $$16 from "./islands/gr-cu/ReferencesManagement.tsx";
import * as $$17 from "./islands/gr-cu/gr-cb-cu/CreateReferenceButton.tsx";
import * as $$18 from "./islands/gr-cu/gr-cb-cu/CreateReferenceDialog.tsx";
import * as $$19 from "./islands/gr-cu/gr-cb-cu/CreateReferenceForm.tsx";
import * as $$20 from "./islands/gr-cu/gr-cb-cu/UpdateReferenceDialog.tsx";
import * as $$21 from "./islands/gr-cu/gr-cb-cu/UpdateReferenceForm.tsx";
import * as $$22 from "./islands/is-cu/LoginForm.tsx";
import * as $$23 from "./islands/is-cu/RegisterForm.tsx";

const manifest = {
  routes: {
    "./routes/(gc-cu)/gestionar-carpetas/(gc-gr-cu)/[id].tsx": $0,
    "./routes/(gc-cu)/gestionar-carpetas/index.tsx": $1,
    "./routes/(gg-cu)/gestionar-grupos/index.tsx": $2,
    "./routes/(gr-cu)/gestionar-referencias/index.tsx": $3,
    "./routes/(is-cu)/inicio-sesion/cerrar-sesion.ts": $4,
    "./routes/(is-cu)/inicio-sesion/index.tsx": $5,
    "./routes/(is-cu)/inicio-sesion/iniciar-sesion.tsx": $6,
    "./routes/(is-cu)/inicio-sesion/registrar.tsx": $7,
    "./routes/_404.tsx": $8,
    "./routes/_app.tsx": $9,
    "./routes/_layout.tsx": $10,
    "./routes/_middleware.ts": $11,
    "./routes/about.tsx": $12,
    "./routes/api/_middleware.ts": $13,
    "./routes/api/bibliographie/[id].tsx": $14,
    "./routes/api/bibliographie/file/[id].tsx": $15,
    "./routes/api/bibliographie/file/index.ts": $16,
    "./routes/api/bibliographie/index.ts": $17,
    "./routes/api/folder/[id].tsx": $18,
    "./routes/api/folder/index.ts": $19,
    "./routes/api/group/[id].tsx": $20,
    "./routes/api/group/index.ts": $21,
    "./routes/api/index.ts": $22,
    "./routes/index.tsx": $23,
    "./routes/suscription.tsx": $24,
  },
  islands: {
    "./islands/Input.tsx": $$0,
    "./islands/PaginationButtons.tsx": $$1,
    "./islands/Select.tsx": $$2,
    "./islands/SessionProvider.tsx": $$3,
    "./islands/gc-cu/CreateFolderButton.tsx": $$4,
    "./islands/gc-cu/CreateFolderCard.tsx": $$5,
    "./islands/gc-cu/DeleteFolderDialog.tsx": $$6,
    "./islands/gc-cu/FolderCard.tsx": $$7,
    "./islands/gc-cu/ListFolders.tsx": $$8,
    "./islands/gg-cu/CreateGroupButton.tsx": $$9,
    "./islands/gg-cu/CreateGroupCard.tsx": $$10,
    "./islands/gg-cu/GroupCard.tsx": $$11,
    "./islands/gg-cu/ListGroups.tsx": $$12,
    "./islands/gr-cu/DeleteReferenceDialog.tsx": $$13,
    "./islands/gr-cu/DownloadFileButton.tsx": $$14,
    "./islands/gr-cu/GenerateReferenceButton.tsx": $$15,
    "./islands/gr-cu/ReferencesManagement.tsx": $$16,
    "./islands/gr-cu/gr-cb-cu/CreateReferenceButton.tsx": $$17,
    "./islands/gr-cu/gr-cb-cu/CreateReferenceDialog.tsx": $$18,
    "./islands/gr-cu/gr-cb-cu/CreateReferenceForm.tsx": $$19,
    "./islands/gr-cu/gr-cb-cu/UpdateReferenceDialog.tsx": $$20,
    "./islands/gr-cu/gr-cb-cu/UpdateReferenceForm.tsx": $$21,
    "./islands/is-cu/LoginForm.tsx": $$22,
    "./islands/is-cu/RegisterForm.tsx": $$23,
  },
  baseUrl: import.meta.url,
};

export default manifest;
